update scripts

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -37,43 +37,52 @@ jobs:
         run: |
           git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3
           rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
+          
+      - name: Setup mkdtimg
+        run: |
+          mkdir -p $GITHUB_WORKSPACE/aosp_tools
+          curl -sL https://android.googlesource.com/platform/system/libufdt/+/refs/heads/master/utils/mkdtimg?format=TEXT | base64 -d > $GITHUB_WORKSPACE/aosp_tools/mkdtimg
+          chmod +x $GITHUB_WORKSPACE/aosp_tools/mkdtimg
+          echo "$GITHUB_WORKSPACE/aosp_tools" >> $GITHUB_PATH
 
       - name: Build Kernel & dtbo.img
         run: |
           export KBUILD_BUILD_USER="Fraschze97"
-          export PATH=$GITHUB_WORKSPACE/greenforce-clang/bin:$PATH
+          export PATH=$GITHUB_WORKSPACE/greenforce-clang/bin:$GITHUB_WORKSPACE/aosp_tools:$PATH
 
           cd kernel-source
           clang -v
 
-          # Set make args
           args="ARCH=arm64 O=../out LD=ld.lld LLVM=1 LLVM_IAS=1"
 
           KFLAGS="-Wno-default-const-init-var-unsafe \
-                    -Wdefault-const-init-field-unsafe \
-                    -Wimplicit-enum-enum-cast \
-                    -Wno-unused-value \
-                    -Wno-type-limits"
+                -Wdefault-const-init-field-unsafe \
+                -Wimplicit-enum-enum-cast \
+                -Wno-unused-value \
+                -Wno-type-limits"
 
           make KCFLAGS="$KFLAGS" $args $KERNEL_CONFIG
-          make -j$(nproc) KCFLAGS="$KFLAGS" $args
+          make -j$(nproc) KCFLAGS="$KFLAGS" $args Image dtb.img dtbo.img
 
       - name: Package kernel
         run: |
-          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3 && rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
-          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
-            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
-          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
-            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
-          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
-            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
-          elif [[ -f out/arch/arm64/boot/Image ]]; then
-            cp out/arch/arm64/boot/Image AnyKernel3/Image
-          fi
-          if [ -f out/arch/arm64/boot/dtbo.img ]; then
-            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
-          fi
+          cd AnyKernel3
 
+          if [[ -f ../out/arch/arm64/boot/Image.gz-dtb ]]; then
+            cp ../out/arch/arm64/boot/Image.gz-dtb Image.gz-dtb
+          elif [[ -f ../out/arch/arm64/boot/Image-dtb ]]; then
+            cp ../out/arch/arm64/boot/Image-dtb Image-dtb
+          elif [[ -f ../out/arch/arm64/boot/Image.gz ]]; then
+            cp ../out/arch/arm64/boot/Image.gz Image.gz
+          elif [[ -f ../out/arch/arm64/boot/Image ]]; then
+            cp ../out/arch/arm64/boot/Image Image
+          else
+            echo "❌ No kernel Image found! Build may have failed." && exit 1
+          fi
+          if [[ -f ../out/arch/arm64/boot/dtbo.img ]]; then
+            cp ../out/arch/arm64/boot/dtbo.img dtbo.img
+          fi
+       
       - name: Package Kernel ZIP
         run: |
           DATE=$(date +%d%m%y)
