up

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -1,15 +1,14 @@
-name: Build Kernel (KernelSU-Next)
-
+name: Build kernel Llvm
 
 on:
   workflow_dispatch:
-
 
 jobs:
   build-kernel:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
+
       - name: Setup environment
         run: |
           echo "ANYKERNEL_SOURCE=$(cat config.env | grep -w "ANYKERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
@@ -19,41 +18,52 @@ jobs:
           echo "KERNEL_CONFIG=$(cat config.env | grep -w "KERNEL_CONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
           echo "BUILD_ARGS=$(cat config.env | grep -w "BUILD_ARGS" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
           sudo apt-get update
-          sudo apt install python2 libncurses5
-          sudo apt-get install libselinux-dev
+          sudo apt install python2 libncurses5 libselinux-dev -y
+
       - name: Pull toolchain
         run: |
           git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
           git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9
           git clone https://github.com/xiangfeidexiaohuo/Snapdragon-LLVM.git clang
-          
+
       - name: Pull kernel source
         run: |
           git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} kernel-source
-          
-      - name: KernelSU-Next
+
+      - name: KernelSU-Next SUSFS
         run: |
           cd kernel-source
           curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
+          cd ..
 
-      - name: Build kernel
+      - name: Checking build DTB
         run: |
-          export KBUILD_BUILD_USER="Reborn"
-          export PATH=$GITHUB_WORKSPACE/clang/bin:${PATH}
-          args="                  ARCH=arm64 \
-                                  O=../out \
-                                  ${{ env.BUILD_ARGS }} \
-                                  CLANG_TRIPLE=aarch64-linux-gnu- \
-                                  CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin/aarch64-linux-android- \
-                                  CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin/arm-linux-androideabi- "
+          export KBUILD_BUILD_USER="Fraschze97"
+          export PATH=$GITHUB_WORKSPACE/clang/bin:$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin:$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin:$PATH
+          args="ARCH=arm64 O=../out CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- ${{ env.BUILD_ARGS }} LLVM=1 LLVM_IAS=1"
           cd kernel-source
           clang -v
           make ${args} ${{ env.KERNEL_CONFIG }}
-          make -j$(nproc --all) ${args}
+          echo "Building DTB..."
+          if make ${args} dtbs; then
+            echo "DTB build succeeded, proceeding..."
+          else
+            echo "Error: Failed to build DTB! Canceling build."
+            exit 1
+          fi
 
+      - name: Build kernel (Full Clang)
+        run: |
+          export PATH=$GITHUB_WORKSPACE/clang/bin:$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin:$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin:$PATH
+          args="ARCH=arm64 O=../out CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- ${{ env.BUILD_ARGS }} LLVM=1 LLVM_IAS=1"
+          cd kernel-source
+          make ${args} ${{ env.KERNEL_CONFIG }}
+          make -j$(nproc --all) ${args} LD=ld.lld
+          
       - name: Package kernel
         run: |
-          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3 && rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
+          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3
+          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
           if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
             cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
           elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
@@ -63,15 +73,19 @@ jobs:
           elif [[ -f out/arch/arm64/boot/Image ]]; then
             cp out/arch/arm64/boot/Image AnyKernel3/Image
           fi
-          if [ -f out/arch/arm64/boot/dtbo.img ]; then
+          if [[ -f out/arch/arm64/boot/dtbo.img ]]; then
             cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
           fi
+          cd AnyKernel3
+          zip -r9 ../DreamsKernel.zip * -x "*.git*" -x "*.md"
+          cd ..
 
       - name: Rename zip with date and random number
         run: |
           DATE=$(date +%d%m%y)
           RAND=$(shuf -i 1000-9999 -n 1)
-          NEW_NAME="Cassia-perf-${DATE}-${RAND}.zip"
+          KERNEL_NAME=$(basename ${{ env.KERNEL_SOURCE }} | sed 's/kernel_//g')
+          NEW_NAME="Cassia-${KERNEL_NAME}-perf-${DATE}-${RAND}-KSU-SUSFS-FC.zip"
           mv DreamsKernel.zip "$NEW_NAME"
           echo "NEW_ZIP_NAME=$NEW_NAME" >> $GITHUB_ENV
 
@@ -88,5 +102,5 @@ jobs:
         run: |
           curl -F document=@"${{ env.NEW_ZIP_NAME }}" \
                -F chat_id=$CHAT_ID \
-               -F caption="Cassia Kernel build ${{ env.NEW_ZIP_NAME }}" \
+               -F caption="Cassia Kernel build: ${{ env.NEW_ZIP_NAME }}" \
                https://api.telegram.org/bot$BOT_TOKEN/sendDocument
